### ISSUE TITLE
Release only from develop/qa/main ... otherwise, create an action ZIP for download

### ISSUE THREAD

**Issue by gkholman** [CraneSoftwrights/board-baseball#253]

**Comment by gkholman** [comment]
Required for return of artefacts:
```
    - name: Create ZIP package of specified directories and files
      run: |
        zip -r crane-baseball-${BRANCH_NAME}-${RELEASE_TIMESTAMP}.zip xyz/ abc/pdf abc/svg abc.png

    - name: Upload artefacts for action 
      uses: actions/upload-artifact@v4
      with:
        name: Packaged artefacts
        path: ${BRANCH_NAME}-${RELEASE_TIMESTAMP}.zip
```
