### ISSUE TITLE
Should the PDF timestamps be homogonized for repository purposes?

### ISSUE THREAD

**Issue by gkholman** [CraneSoftwrights/board-baseball#261]
Comme ça:
```
name: Generate PDF with Fixed Timestamp

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Inkscape
      run: sudo apt-get install inkscape

    - name: Install exiftool
      run: sudo apt-get install libimage-exiftool-perl

    - name: Export SVG to PDF
      run: inkscape path/to/yourfile.svg --export-filename=output.pdf

    - name: Set fixed timestamp
      run: exiftool -AllDates="2024:01:01 00:00:00" output.pdf

    - name: Remove exiftool backup file
      run: rm -f output.pdf_original

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: output-pdf
        path: output.pdf

```
